// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Main Navigation → Navigation Items*
 */
export interface MainNavigationDocumentDataNavigationItemsItem {
  /**
   * Navigation Label field in *Main Navigation → Navigation Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Home, Services, Projects
   * - **API ID Path**: main_navigation.navigation_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Navigation Link field in *Main Navigation → Navigation Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Internal link, external URL, or document
   * - **API ID Path**: main_navigation.navigation_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Main Navigation documents
 */
interface MainNavigationDocumentData {
  /**
   * Navigation Items field in *Main Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: main_navigation.navigation_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_items: prismic.GroupField<
    Simplify<MainNavigationDocumentDataNavigationItemsItem>
  >;
}

/**
 * Main Navigation document from Prismic
 *
 * - **API ID**: `main_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainNavigationDocumentData>,
    "main_navigation",
    Lang
  >;

type ProjectPageDocumentDataSlicesSlice =
  | FaqSlice
  | ImageGallerySlice
  | RichTextContentSlice
  | HeroSlice;

/**
 * Content for Project Page documents
 */
interface ProjectPageDocumentData {
  /**
   * Project Title field in *Project Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.project_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_title: prismic.KeyTextField;

  /**
   * Location field in *Project Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Project Type field in *Project Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Interior Design
   * - **API ID Path**: project_page.project_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  project_type: prismic.SelectField<
    "Interior Design" | "Remodal/Renovation" | "New Construction",
    "filled"
  >;

  /**
   * Primary Room field in *Project Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.primary_room
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  primary_room: prismic.SelectField<
    | "Bathroom"
    | "Bedroom"
    | "Home Bar"
    | "Kitchen   "
    | "Living Room"
    | "Lower Level"
    | "Master Suite"
    | "Whole"
    | "Wine Cellar"
  >;

  /**
   * Design Style field in *Project Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.design_style
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  design_style: prismic.SelectField<
    "Contemporary" | "Eclectic" | "Luxury" | "Open Concept" | "Traditional"
  >;

  /**
   * Completion Date field in *Project Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.completion_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  completion_date: prismic.DateField;

  /**
   * Hero Image field in *Project Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Project Description field in *Project Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.project_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * Slice Zone field in *Project Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectPageDocumentDataSlicesSlice>;
}

/**
 * Project Page document from Prismic
 *
 * - **API ID**: `project_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectPageDocumentData>,
    "project_page",
    Lang
  >;

type ServicePageDocumentDataSlicesSlice = never;

type ServicePageDocumentDataSlices1Slice = never;

/**
 * Content for Service Page documents
 */
interface ServicePageDocumentData {
  /**
   * Title field in *Service Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Hero Image field in *Service Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Short Description field in *Service Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Slice Zone field in *Service Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServicePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Service Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * `slices1` field in *Service Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_page.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices1: prismic.SliceZone<ServicePageDocumentDataSlices1Slice>;
}

/**
 * Service Page document from Prismic
 *
 * - **API ID**: `service_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicePageDocumentData>,
    "service_page",
    Lang
  >;

type StandardPageDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Standard Page documents
 */
interface StandardPageDocumentData {
  /**
   * Title field in *Standard Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Hero Image field in *Standard Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Standard Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<StandardPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Standard Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: standard_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Standard Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: standard_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Standard Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: standard_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Standard Page document from Prismic
 *
 * - **API ID**: `standard_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StandardPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<StandardPageDocumentData>,
    "standard_page",
    Lang
  >;

/**
 * Content for Team Member documents
 */
interface TeamMemberDocumentData {
  /**
   * Name field in *Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *Team Member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Bio field in *Team Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Headshot field in *Team Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_member.headshot
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  headshot: prismic.ImageField<never>;
}

/**
 * Team Member document from Prismic
 *
 * - **API ID**: `team_member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamMemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TeamMemberDocumentData>,
    "team_member",
    Lang
  >;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
  /**
   * Client Name field in *Testimonial*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.client_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField;

  /**
   * Quote field in *Testimonial*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Project Link field in *Testimonial*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project_link: prismic.ContentRelationshipField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialDocumentData>,
    "testimonial",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | MainNavigationDocument
  | ProjectPageDocument
  | ServicePageDocument
  | StandardPageDocument
  | TeamMemberDocument
  | TestimonialDocument;

/**
 * Primary content in *FAQ → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Tagline field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: FAQ section
   * - **API ID Path**: faq.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Frequently Asked Questions
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We've compiled the most important information to help you get the most out of your interior design experience. Can't find what you're looking for?
   * - **API ID Path**: faq.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Contact Link Text field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact us
   * - **API ID Path**: faq.default.primary.contact_link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_link_text: prismic.KeyTextField;

  /**
   * Contact Link field in *FAQ → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a page or enter URL
   * - **API ID Path**: faq.default.primary.contact_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  contact_link: prismic.LinkField;
}

/**
 * Primary content in *FAQ → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Question field in *FAQ → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your question here...
   * - **API ID Path**: faq.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FAQ → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your answer here...
   * - **API ID Path**: faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for FAQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *FAQ*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * FAQ Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: FAQ
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Hero → Text Left → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Text Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your hero title...
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Text Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your hero subtitle...
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Text Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * CTA Button Label field in *Hero → Text Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Get Started, Learn More
   * - **API ID Path**: hero.default.primary.cta_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_label: prismic.KeyTextField;

  /**
   * CTA Button Link field in *Hero → Text Left → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a page or enter URL
   * - **API ID Path**: hero.default.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Overlay Opacity field in *Hero → Text Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose overlay darkness
   * - **API ID Path**: hero.default.primary.overlay_opacity
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  overlay_opacity: prismic.SelectField<"none" | "light" | "medium" | "dark">;
}

/**
 * Text Left variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Text Centered → Primary*
 */
export interface HeroSliceTextCenteredPrimary {
  /**
   * Title field in *Hero → Text Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your hero title...
   * - **API ID Path**: hero.textCentered.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Text Centered → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your hero subtitle...
   * - **API ID Path**: hero.textCentered.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Background Image field in *Hero → Text Centered → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.textCentered.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * CTA Button Label field in *Hero → Text Centered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Get Started, Learn More
   * - **API ID Path**: hero.textCentered.primary.cta_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button_label: prismic.KeyTextField;

  /**
   * CTA Button Link field in *Hero → Text Centered → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a page or enter URL
   * - **API ID Path**: hero.textCentered.primary.cta_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Overlay Opacity field in *Hero → Text Centered → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose overlay darkness
   * - **API ID Path**: hero.textCentered.primary.overlay_opacity
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  overlay_opacity: prismic.SelectField<"none" | "light" | "medium" | "dark">;
}

/**
 * Text Centered variation for Hero Slice
 *
 * - **API ID**: `textCentered`
 * - **Description**: Hero with centered text layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceTextCentered = prismic.SharedSliceVariation<
  "textCentered",
  Simplify<HeroSliceTextCenteredPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceTextCentered;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
  /**
   * Gallery Image field in *ImageGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.items[].gallery_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gallery_image: prismic.ImageField<never>;

  /**
   * Caption field in *ImageGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional image caption
   * - **API ID Path**: image_gallery.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: Image Gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Primary content in *Rich Text Content → Default → Primary*
 */
export interface RichTextContentSliceDefaultPrimary {
  /**
   * Content field in *Rich Text Content → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter your content here...
   * - **API ID Path**: rich_text_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Text Alignment field in *Rich Text Content → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose alignment
   * - **Default Value**: left
   * - **API ID Path**: rich_text_content.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_alignment: prismic.SelectField<
    "left" | "center" | "right" | "justify",
    "filled"
  >;

  /**
   * Text Size field in *Rich Text Content → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose text size
   * - **Default Value**: medium
   * - **API ID Path**: rich_text_content.default.primary.text_size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_size: prismic.SelectField<"small" | "medium" | "large", "filled">;

  /**
   * Background Color field in *Rich Text Content → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose background
   * - **Default Value**: none
   * - **API ID Path**: rich_text_content.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    "none" | "light-gray" | "dark-gray" | "blue" | "white",
    "filled"
  >;
}

/**
 * Default variation for Rich Text Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default rich text content block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Rich Text Content*
 */
type RichTextContentSliceVariation = RichTextContentSliceDefault;

/**
 * Rich Text Content Shared Slice
 *
 * - **API ID**: `rich_text_content`
 * - **Description**: A flexible Slice for general text content, allowing for headings, paragraphs, lists, and embedded images.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextContentSlice = prismic.SharedSlice<
  "rich_text_content",
  RichTextContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MainNavigationDocument,
      MainNavigationDocumentData,
      MainNavigationDocumentDataNavigationItemsItem,
      ProjectPageDocument,
      ProjectPageDocumentData,
      ProjectPageDocumentDataSlicesSlice,
      ServicePageDocument,
      ServicePageDocumentData,
      ServicePageDocumentDataSlicesSlice,
      ServicePageDocumentDataSlices1Slice,
      StandardPageDocument,
      StandardPageDocumentData,
      StandardPageDocumentDataSlicesSlice,
      TeamMemberDocument,
      TeamMemberDocumentData,
      TestimonialDocument,
      TestimonialDocumentData,
      AllDocumentTypes,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceTextCenteredPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceTextCentered,
      ImageGallerySlice,
      ImageGallerySliceDefaultItem,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      RichTextContentSlice,
      RichTextContentSliceDefaultPrimary,
      RichTextContentSliceVariation,
      RichTextContentSliceDefault,
    };
  }
}
